
# Global parameters -------------------

# Option to save time by not running blastx
run_blastx: False

# Upload results to zenodo
# For upload, setup ZENODO_PAT environment variable for access_token
zenodo:
    deposition_id:

# path or URL to sample sheet (CSV format, columns: sample, condition, ...)
samples: samples.tsv

# Path to RepeatMasker Repbase file (path/to/RMRBSeqs.embl)
repbase_file: "/gpfs/hpchome/taavi74/databases/Repbase/Libraries/RMRBSeqs.embl"

# Path to reference genome
ref_genome: "/gpfs/software/VirusSeeker/databases/ref_genomes/human_g1k_v37.fasta"
ref_bacteria: "/gpfs/software/VirusSeeker/databases/bacteria_ref_sequence/Bacteria_ref_genome.fna"

# Path to virus database
virus_nt: "/gpfs/software/VirusSeeker/databases/VirusDBNT_20160802/VirusDBNT_20160802_ID98.fa"
virus_nr: "/gpfs/software/VirusSeeker/databases/VirusDBNR_20160802/VirusDBNR_20160802_ID98.fa"

# Path to taxonomy database
vhunter: "/gpfs/software/VirusSeeker/databases/taxdump_300817/vhunter.db"
names: "/gpfs/software/VirusSeeker/databases/taxdump_300817/names.dmp"
nodes: "/gpfs/software/VirusSeeker/databases/taxdump_300817/nodes.dmp"
division: "/gpfs/software/VirusSeeker/databases/taxdump_300817/division.dmp"

# Paths to nt and nr blast database to be used for environment variable
nt: "/gpfs/software/VirusSeeker/databases/nt/nt"
nr: "/gpfs/software/VirusSeeker/databases/nr/nr"

# Rule parameters ---------------------

# fastq-join
fastq-join:
    maximum_difference: 5
    minimum_overlap: 10

# Filter repeatmasker and tantan output
filter_ns:
    min_length: 50
    por_n: 40

# Split fasta
split_fasta:
    n_files: 2

# MegaBlast against reference genome to remove more host sequences
megablast_ref_genome:
    perc_identity: 85
    evalue: 1e-10
    word_size: 16
    max_hsps: 1

# MegaBlast against NT to remove more host sequences
megablast_nt:
    evalue: 1e-8
    word_size: 16
    max_hsps: 50
    max_target_seqs: 5

# Blastn against virus nucleotide database
blastn_virus:
    evalue: 1e-4
    db_soft_mask: 100
    max_hsps: 50

# Blastx against virus protein database
blastx_virus:
    evalue: 1e-2
    db_soft_mask: 100
    max_hsps: 50

# Blastn against nucleotide database
blastn_nt:
    evalue: 1e-8
    max_hsps: 50

# Blastx against protein database
blastx_nr:
    evalue: 1e-2
    max_hsps: 50
