
# Global parameters -------------------

# Set seed for fastq downsampling
seed: 561837

# Path or URL to sample sheet (TSV format, required columns: sample, fq1, fq2, frac)
# sample - unique sample name
# fq1 and fq2 - paths to paired-end fastq file
# frac - fraction of reads to sample. Set it to 0 or >=1 for no downsampling. Check and set also seed in config.yml to make results reproducible.
samples: "samples.tsv"
remote: True

# Option to save time by not running blastx
run_blastx: False

# Upload results to zenodo
# For upload, setup ZENODO_PAT environment variable for access_token
zenodo:
    deposition_id: 1488086

# Remote FTP credentials
username: "anonymous"
password: "taavi.pall@ut.ee"

# Split fasta
split_fasta:
    n_files: 20

# Path to RepeatMasker Repbase file (path/to/RMRBSeqs.embl)
repbase_file: /gpfs/hpchome/radko/Libraries/RMRBSeqs.embl

# Path to reference genome
ref_genome: /gpfs/hpc/repository/VirusSeeker/databases/ref_genomes/human_g1k_v37.fasta
ref_bacteria: /gpfs/hpc/repository/VirusSeeker/databases/bacteria_ref_sequence/Bacteria_ref_genome.fna

# Path to virus database
virus_nt: /gpfs/hpc/repository/VirusSeeker/databases/VirusDBNT_20160802/VirusDBNT_20160802_ID98.fa
virus_nr: /gpfs/hpc/repository/VirusSeeker/databases/VirusDBNR_20160802/VirusDBNR_20160802_ID98.fa

# Path to taxonomy database
vhunter: /gpfs/hpc/repository/VirusSeeker/databases/taxdump_300817/vhunter.db
names: /gpfs/hpc/repository/VirusSeeker/databases/taxdump_300817/names.dmp
nodes: /gpfs/hpc/repository/VirusSeeker/databases/taxdump_300817/nodes.dmp
division: /gpfs/hpc/repository/VirusSeeker/databases/taxdump_300817/division.dmp

# Paths to nt and nr blast database to be used for environment variable
nt: /gpfs/hpc/repository/VirusSeeker/databases/nt/nt
nr: /gpfs/hpc/repository/VirusSeeker/databases/nr/nr

# Rule parameters ---------------------
# Modify these settings only when you know what you are doing
# Filter repeatmasker and tantan output
filter_ns:
    min_length: 50
    por_n: 40

# MegaBlast against reference genome to remove more host sequences
megablast_ref_genome:
    perc_identity: 85
    evalue: 1e-10
    word_size: 16
    max_hsps: 1

# MegaBlast against NT to remove more host sequences
megablast_nt:
    evalue: 1e-8
    word_size: 16
    max_hsps: 50
    max_target_seqs: 5

# Blastn against virus nucleotide database
blastn_virus:
    evalue: 1e-4
    db_soft_mask: 100
    max_hsps: 50

# Blastx against virus protein database
blastx_virus:
    evalue: 1e-2
    db_soft_mask: 100
    max_hsps: 50

# Blastn against nucleotide database
blastn_nt:
    evalue: 1e-8
    max_hsps: 50

# Blastx against protein database
blastx_nr:
    evalue: 1e-2
    max_hsps: 50

# Wrapper urls
wrappers:
    blast: https://bitbucket.org/tpall/snakemake-wrappers/raw/c95af40e7bfb10a8d213c2f63dd2b79d29ebcbf2/bio/blast/query
    parse_blast: https://bitbucket.org/tpall/snakemake-wrappers/raw/c95af40e7bfb10a8d213c2f63dd2b79d29ebcbf2/bio/blast/parse
    blast_taxonomy: https://bitbucket.org/tpall/snakemake-wrappers/raw/c95af40e7bfb10a8d213c2f63dd2b79d29ebcbf2/bio/blast/taxonomy
    stats: https://bitbucket.org/tpall/snakemake-wrappers/raw/e7699c0ae37a999909fb764c91723d46ded7461c/bio/seqkit/stats
