
# Set seed for fastq downsampling
seed: 561837

# Path or URL to sample sheet (TSV format, required columns: sample, fq1, fq2, frac)
# sample - unique sample name
# fq1 and fq2 - paths to paired-end fastq file
# frac - fraction of reads to sample. Set it to 0 or >=1 for no downsampling. Check and set also seed in config.yml to make results reproducible.
samples: "samples.tsv"
# Set remote to True when sample paths point to ftp site
remote: True

# Option to save time by not running blastx
run_blastx: False

# Upload results to zenodo
# For upload, setup ZENODO_PAT environment variable for access_token
zenodo:
    deposition_id: 1488086

# Remote FTP credentials
username: "anonymous"
password: "taavi.pall@ut.ee"

# Split fasta
split_fasta:
    n_files: 20
