$schema: "http://json-schema.org/draft-07/schema#"
description: snakemake configuration file
properties:
  seed:
    type: integer
    default: 11
    description: an integer, seed for fastq sample
  samples:
    type: string
    description: path to samples.tsv file
  remote:
    type: boolean
    default: false
    description: boolean that indicates whether to download remote files via FTP
  username:
    type: string
    description: username for remote file FTP download
  password:
    type: string
    description: password for remote file FTP download
  run_blastx:
    type: boolean
    default: false
    description: boolean that switches in/out option to save time by not running blastx
  zenodo:
    deposition_id:
      type: ["string", "null"]
      default: null
  split_fasta:
    n_files:
      type: integer
      default: 20
      description: number of files to split fasta file before repeatmasker, defaults to 2
    required:
      - n_files
  repbase_file:
    type: string
    description: path to RepeatMasker Repbase file (path/to/RMRBSeqs.embl)
  ref_genome:
    type: string
    description:  path to host reference genome database
  ref_bacteria:
    type: string
    description:  path to bacterial reference genome database
  virus_nt:
    type: string
    description:  path to virus nucleotide sequence database
  virus_nr:
    type: string
    description:  path to virus protein database
  vhunter:
    type: string
    description:  path to virus taxonomy database
  names:
    type: string
    description:  path to species names database
  nodes:
    type: string
    description:  path to taxonomy nodes database
  division:
    type: string
    description:  path to taxonomic division database
  nt:
    type: string
    description: path to nt blast database
  nr:
    type: string
    description: path to nr blast database
  filter_ns:
    min_length:
      type: integer
      default: 50
    por_n:
      type: integer
      default: 40
    required:
      - min_length
      - por_n
  megablast_ref_genome:
    perc_identity:
      type: integer
      default: 85
    evalue:
      type: integer
      default: 1e-10
    word_size:
      type: integer
      default: 16
    max_hsps:
      type: integer
      default: 1
    required:
      - perc_identity
      - evalue
      - word_size
      - max_hsps
  megablast_nt:
    evalue:
      type: integer
      default: 1e-8
    word_size:
      type: integer
      default: 16
    max_hsps:
      type: integer
      default: 50
    max_target_seqs:
      type: integer
      default: 5
    required:
      - evalue
      - word_size
      - max_hsps
      - max_target_seqs
  blastn_virus:
    evalue:
      type: integer
      default: 1e-4
    db_soft_mask:
      type: integer
      default: 100
    max_hsps:
      type: integer
      default: 50
    required:
      - evalue
      - db_soft_mask
      - max_hsps
  blastx_virus:
    evalue:
      type: integer
      default: 1e-2
    db_soft_mask:
      type: integer
      default: 100
    max_hsps:
      type: integer
      default: 50
    required:
      - evalue
      - db_soft_mask
      - max_hsps
  blastn_nt:
    evalue:
      type: integer
      default: 1e-8
    max_hsps:
      type: integer
      default: 50
    required:
      - evalue
      - max_hsps
  blastx_nr:
    evalue:
      type: integer
      default: 1e-2
    max_hsps:
      type: integer
      default: 50
    required:
      - evalue
      - max_hsps
  wrappers:
    sample:
      type: string
    fastp:
      type: string
    fastq_join:
      type: string
    blast:
      type: string
    parse_blast:
      type: string
    upload:
      type: string
    required:
      - fastq_join
      - fastp
      - sample
      - blast
      - parse_blast
      - upload

required:
  - samples
  - split_fasta
  - repbase_file
  - ref_genome
  - ref_bacteria
  - virus_nt
  - virus_nr
  - vhunter
  - names
  - nodes
  - division
  - nt
  - nr
