$schema: "http://json-schema.org/draft-07/schema#"
description: snakemake configuration file
type: object
properties:
  seed:
    type: integer
    default: 11
    description: an integer, seed for fastq sample
  samples:
    type: string
    description: path to samples.tsv file
  remote:
    type: boolean
    default: false
    description: boolean that indicates whether to download remote files via FTP
  run_blastx:
    type: boolean
    default: false
    description: boolean that switches in/out option to save time by not running blastx

required:
  - samples

